[package]
name = "crypto-clippy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arboard = "2.1.1"
tokio = { version = "1.19.2", features = ["full"] }
regex = "1"
lazy_static = "1.4.0"